// <auto-generated />
using FurnitureOrder.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace backend.Migrations.OrderLineDbMigrations
{
    [DbContext(typeof(OrderLineDb))]
    partial class OrderLineDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("FurnitureOrder.Models.OrderLine", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("finalPrice")
                        .HasColumnType("REAL");

                    b.Property<int>("order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("product")
                        .HasColumnType("INTEGER");

                    b.Property<int>("quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("OrderLine");
                });
#pragma warning restore 612, 618
        }
    }
}
