// <auto-generated />
using System;
using FurnitureRebate.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace backend.Migrations.RebateDbMigrations
{
    [DbContext(typeof(RebateDb))]
    [Migration("20220408160904_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("FurnitureRebate.Models.Rebate", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("category_rebate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("TEXT");

                    b.Property<float>("percentage")
                        .HasColumnType("REAL");

                    b.Property<int>("product")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("product_specific")
                        .HasColumnType("INTEGER");

                    b.Property<string>("subject")
                        .HasColumnType("TEXT");

                    b.Property<float>("value")
                        .HasColumnType("REAL");

                    b.HasKey("id");

                    b.ToTable("Rebate");
                });
#pragma warning restore 612, 618
        }
    }
}
