// <auto-generated />
using System;
using FurnitureRebate.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace backend.Migrations.RebateDbMigrations
{
    [DbContext(typeof(RebateDb))]
    partial class RebateDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("FurnitureProduct.Models.Product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("category")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("TEXT");

                    b.Property<bool>("is_active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<float?>("price")
                        .HasColumnType("REAL");

                    b.HasKey("id");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("FurnitureRebate.Models.Rebate", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("category_rebate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("TEXT");

                    b.Property<float>("percentage")
                        .HasColumnType("REAL");

                    b.Property<bool>("product_specific")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("productid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("subject")
                        .HasColumnType("TEXT");

                    b.Property<float>("value")
                        .HasColumnType("REAL");

                    b.HasKey("id");

                    b.HasIndex("productid");

                    b.ToTable("Rebate");
                });

            modelBuilder.Entity("FurnitureRebate.Models.Rebate", b =>
                {
                    b.HasOne("FurnitureProduct.Models.Product", "product")
                        .WithMany()
                        .HasForeignKey("productid");

                    b.Navigation("product");
                });
#pragma warning restore 612, 618
        }
    }
}
